### ISSUE TITLE
Windows issues

### ISSUE THREAD

**Issue by jsahlen** [jsahlen/gulp-css-globbing#3]
As discussed in #1, there seems to be issues on Windows environments (possibly related to regexes?)

**Comment by Rob-ot** [comment]
It's working for me on windows, seems like it does some interesting / and \ switching stuff with glob but it gets the job done. Close this issue?

**Comment by jsahlen** [comment]
Thanks for letting me know. I'll close, and if someone else has any problems, we'll open a new one.
